theme: osuny
_merge: deep
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  debug:
    productionUrl: "https://www.communication-democratie.org"
  home:
    head:
      title: site
  logo: 
    footer: "/assets/images/logo-footer.svg"
  menu:
    primary:
      level_2:
        summary:
          active: true
          source: meta_description
          truncate: false
  pages:
    index:
      truncate_description: 250
  plausible: communication-democratie.org
  posts:
    index:
      layout: grid
      options:
        authors: true
  summary:
    position: content
