theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: communication-democratie.org
  summary:
    position: content
  logo: 
    footer: "/assets/images/logo-footer.svg"
  posts:
    index:
      truncate_description: 200
      layout: grid
      options:
        hide_author: false
  pages:
    index:
      truncate_description: 250
  breadcrumb:
    position: after-hero
  debug:
    productionUrl: "https://www.communication-democratie.org"


