theme: osuny
_merge: deep
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: communication-democratie.org
  summary:
    position: content
  logo: 
    footer: "/assets/images/logo-footer.svg"
  menu:
    primary:
      level_2:
        summary:
          active: true
          source: meta_description
          truncate: false
  posts:
    index:
      layout: grid
      options:
        authors: true
  pages:
    index:
      truncate_description: 250
  breadcrumb:
    position: after-hero
  debug:
    productionUrl: "https://www.communication-democratie.org"


