on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 2 * * *'

name: 'Daily W3C Validation'

jobs:
  validate:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    name: 'Validate against W3C'
    strategy:
      matrix:
        url:
          - https://www.communication-democratie.org/fr/
          - https://www.communication-democratie.org/fr/enjeux/communication-et-rse/
          - https://www.communication-democratie.org/fr/l-association/organes-et-fonctionnement/
          - https://www.communication-democratie.org/fr/publications/actualites/
          - https://www.communication-democratie.org/fr/publications/2024-02-27-conference-2-ans-apres-la-loi-climat/
    steps:
      - name: Send request to W3C with URL to validate
        run: |
          curl -G "https://validator.w3.org/nu/" --data-urlencode "doc=${{ matrix.url }}" --data-urlencode "out=json" > w3c-response.json
      - name: Send JSON response to webhook
        run: |
          curl --write-out '%{http_code}' --silent --output /dev/null -X POST -H "Content-Type: application/json" -H "X-Secret-Token: ${{ secrets.W3C_CI_API_SECRET }}" -d @w3c-response.json ${{ secrets.W3C_CI_API_URL }}
